export const ADD_TO_INVENTORY = 'ADD_TO_INVENTORY'
export const REMOVE_FROM_INVENTORY = 'REMOVE_FROM_INVENTORY'
export const LOADING_STATUS = 'LOADING_STATUS'
export const UPDATE_INVENTORY = 'UPDATE_INVENTORY'